### ISSUE TITLE
LastUpdate/Linear Extrapolation Consistency

### ISSUE THREAD

**Issue by McChimp** [khronion/Spyglass#5]
LastUpdate gives the time a region started updating whereas linear extrapolation predicts the time it will finish updating.
Consider making SG consistent with linear extrapolation.

:)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

**Comment by khronion** [comment]
For consistency's sake, we'll have all times reflect the start of a region's update.

I'll also change the sheets to list both linear extrapolation and LASTUPDATE for major update.
